#!/bin/sh

set -e

if [ "$UID" -ne 0 ]; then
    echo run as root
    exit 1
fi

if [ "$#" -ne 1 ] && [ "$#" -ne 4 ] && [ "$#" -ne 5 ]; then
    echo usage: configure-dhcp name [ ip default-gateway dns [ ip6 ] ]
    exit 1
fi

NAME="$1"

sed -i '/'"$NAME"'/d' /etc/dhcpcd.conf

if [ "$#" -ne 1 ]; then
    IP="$2"
    GATEWAY="$3"
    DNS="$4"
    cat >> /etc/dhcpcd.conf <<EOF
# define static route $NAME
interface $NAME # $NAME
static ip_address=$IP # $NAME
EOF
    IP6="$5"
    if ! [ -z "$IP6" ]; then
        cat >> /etc/dhcpcd.conf <<EOF
static ip6_address=$IP6 # $NAME
EOF
    fi
    cat >> /etc/dhcpcd.conf <<EOF
static routers=$GATEWAY # $NAME
static domain_name_servers=$DNS # $NAME
EOF
fi

systemctl enable "dhcpcd@$NAME"
systemctl start "dhcpcd@$NAME"
