#!/bin/sh

set -e

if [ "$UID" -ne 0 ]; then
    echo run as root
    exit 1
fi

if [ "$#" -ne 3 ]; then
    echo usage: create-disks vm-name disk-size vg
    exit 1
fi

lvcreate -y -n "$1-disk"  -L "$2" "$3"
