#!/bin/sh

set -e

if [ "$UID" -ne 0 ]; then
    echo run as root
    exit 1
fi

if [ "$#" -ne 2 ] && [ "$#" -le 4 ]; then
    echo usage: create-bridge name interfaces [ ip default-gateway dns ]
    exit 1
fi

NAME="$1"
PHYS="$2"

cat >> /etc/netctl/bridge-$NAME <<EOF
Description="$NAME Bridge connection"
Interface=$NAME
Connection=bridge
BindsToInterfaces=($PHYS)
## Use the MAC address of eth1 (may also be set to a literal MAC address)
#MACAddress=eth1
IP=dhcp
## Ignore (R)STP and immediately activate the bridge
#SkipForwardingDelay=yes c'est wow de ouf
EOF

netctl enable "bridge-$NAME"
netctl start "bridge-$NAME"

shift 2

configure-dhcp "$NAME" $@
