#!/bin/sh

if [ "$UID" -ne 0 ]; then
    echo run as root
    exit 1
fi

if [ "$#" -gt 1 ]; then
    echo usage: get-shell-script [ script-name ]
    exit 1
fi

if [ "$#" -eq 1 ]; then
    NAME="$1"
else
    NAME="script"
fi


xenstore-read /local/domain/$(xenstore-read domid)/"$NAME" \
    | sed 's/\\n/\n/g' > "$NAME" && chmod 755 "$NAME"
