#!/bin/sh

if [ "$UID" -ne 0 ]; then
    echo run as root
    exit 1
fi

if [ "$#" -ne 1 ]; then
    echo usage: get-shell-script NAME
    exit 1
fi

NAME="$1"

xenstore-read /local/domain/$(xenstore-read domid)/"$NAME" \
    | sed 's/\\n/\n/g' \
    | sed 's/\\t/\t/g' > "$NAME" && chmod 755 "$NAME"
