#!/bin/sh

if [ "$UID" -ne 0 ]; then
    echo run as root
    exit 1
fi

if [ "$#" -ne 3 ] && [ "$#" -ne 2 ]; then
    echo usage: register-shell-script DOMAIN NAME [ SCRIPT ]
    exit 1
fi

DOMAIN="$1"
NAME="$2"

if [ "$#" -eq 3 ]; then
    SCRIPT="$3"
    xenstore-write /local/domain/$(get-dom-id $DOMAIN)/"$NAME" "$(cat $SCRIPT)"
else
    xenstore-write /local/domain/$(get-dom-id $DOMAIN)/"$NAME" "$(cat)"
fi
