#!/bin/sh

if [ "$UID" -ne 0 ]; then
    echo run as root
    exit 1
fi

if [ "$#" -ne 2 ]; then
    echo usage: set-variable DOMAIN NAME VALUE
    exit 1
fi

DOMAIN="$1"
NAME="$2"
VARIABLE="$3"

xenstore-write /local/domain/$(get-dom-id $DOMAIN)/"$NAME" "$VARIABLE"
